# Generated by Django 3.1.2 on 2020-10-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_ischangedpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_passwords', models.TextField(blank=True, default='')),
            ],
        ),
    ]
