# Generated by Django 3.1.2 on 2020-10-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201007_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
